### ISSUE TITLE
Launching jetconf: ImportError: No module named 'yangson.schema'

### ISSUE THREAD

**Issue by syedsk** [CZ-NIC/jetconf#1]
I installed jetconf on ubuntu 15. But when I tried to start I see this error:

  File "/home/osboxes/.local/lib/python3.5/site-packages/jetconf/__main__.py", line 13, in <module>
      from yangson.schema import SchemaError, SemanticError
 ImportError: No module named 'yangson.schema'

**Comment by llhotka** [comment]
JetConf got out of sync with the recent (1.3) release of the [yangson](https://github.com/CZ-NIC/yangson) library. We will make a new release of JetConf soon (hopefully next week).

Sorry for this.
