### ISSUE TITLE
I got this error when attempting to start jetconf

### ISSUE THREAD

**Issue by xianglisegue** [CZ-NIC/jetconf#6]
Hi
I am on MacOS, Python3.5, installed jetconf using 
pip3 install jetconf

All dependency including yangson-1.3.15 appears to have been automatically found and installed successfully , as shown below:
Xiangs-MacBook-Pro:bin xiangli$ pip3 install jetconf
Collecting jetconf
  Using cached jetconf-0.1.2-py3-none-any.whl
Collecting yangson (from jetconf)
  Using cached yangson-1.3.15-py3-none-any.whl
Collecting colorlog (from jetconf)
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Collecting h2 (from jetconf)
  Using cached h2-3.0.1-py2.py3-none-any.whl
Collecting PyXB (from yangson->jetconf)
  Using cached PyXB-1.2.5.tar.gz
Collecting hpack<4,>=2.3 (from h2->jetconf)
  Using cached hpack-3.0.0-py2.py3-none-any.whl
Collecting hyperframe<6,>=5.0 (from h2->jetconf)
  Using cached hyperframe-5.1.0-py2.py3-none-any.whl
Installing collected packages: PyXB, yangson, colorlog, hpack, hyperframe, h2, jetconf
  Running setup.py install for PyXB
Successfully installed PyXB-1.2.5 colorlog-2.10.0 h2-3.0.1 hpack-3.0.0 hyperframe-5.1.0 jetconf-0.1.2 yangson-1.3.15

But when I tried to start jetconf the following error message was raised:

Xiangs-MacBook-Pro:bin xiangli$ ./jetconf 
Traceback (most recent call last):
  File "./jetconf", line 7, in <module>
    from jetconf.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jetconf/__main__.py", line 13, in <module>
    from yangson.schema import SchemaError, SemanticError
ImportError: No module named 'yangson.schema'

Can you help me determine what's wrong? Is there a get-started document or tutorial? I looked at the documentation available none of them talks about how to configure jetconf and then start it after installation. A few sample requests to help users verify if installation is successful would be extremely helpful.

Thank you,
-Xiang

**Comment by pspirek** [comment]
Hello, there was a very old development version on PyPI, so I made an update today. Because Jetconf is a live project and undergoes rapid changes, we recommend installing from Git if you would like to follow its development.

There is also some documentation available on our GitLab wiki, please take a look: https://gitlab.labs.nic.cz/labs/jetconf/wikis/home

**Comment by xianglisegue** [comment]
thanks! I upgraded to the latest version you loaded. But still  got the import error complaining about from h2.errors import PROTOCOL_ERROR etc. 
It looks the code does not work with the latest h2 3.0.1 that is installed by pip automatically. 
After I downgraded h2 to 2.5.2, no more import error. But I am left with a message:

C:\Users\Xiang Li\AppData\Local\Programs\Python\Python36-32\Scripts>jetconf.exe
Configuration file does not exist

Can you point any document that shows how do I create a configuration file to start jetconf?

Thanks,
-Xiang

**Comment by pspirek** [comment]
Yes, Jetconf needs h2 version 2.5-2.6, which is stated in requirements.txt. I will take a look on PIP's behaviour.

You can find an example configuration file in Jetconf git repo, under `data/example-config.yaml`, then modify it to your needs. All configuration options are described on the GitLab wiki. Jetconf also needs a backend package to work, I recommed using "dummy" jukebox demo backend to get started (link available on GitLab wiki). Install it by cloning its Git repo, then
`python3 setup.py install`
The backend repo also contains a necessary YANG library (under `yang-data` and example data file `example-data.json`)

Thanks for your interest.

**Comment by xianglisegue** [comment]
Thanks! That is a really important piece of info! I think it should be added into a README  file or some other get-started document.

Now I can start jetconf server successfully with sample data as well as sample certificate:
ubuntu@ip-172-26-8-91:~$ jetconf -c /home/ubuntu/jetconf-conf/jetconf-config.yaml
2017-06-29 02:45:34,801 INFO     Using config:
GLOBAL:
  BACKEND_PACKAGE: jetconf_jukebox
  DATA_JSON_FILE: /home/ubuntu/jetconf-conf/example-data.json
  LOGFILE: '-'
  LOG_DBG_MODULES:
  - usr_conf_data_handlers
  - knot_api
  - nacm
  - data
  LOG_LEVEL: debug
  PERSISTENT_CHANGES: false
  PIDFILE: /tmp/jetconf.pid
  TIMEZONE: Europe/Prague
  VALIDATE_TRANSACTIONS: true
  YANG_LIB_DIR: /home/ubuntu/jetconf-conf/yang-data-jukebox
HTTP_SERVER:
  API_ROOT: /restconf
  API_ROOT_RUNNING: /restconf_running
  CA_CERT: /home/ubuntu/jetconf-conf/ca.pem
  DBG_DISABLE_CERTS: false
  DOC_DEFAULT_NAME: index.html
  DOC_ROOT: /home/ubuntu/jetconf-conf/doc-root
  LISTEN_LOCALHOST_ONLY: false
  PORT: 8443
  SERVER_NAME: jetconf-h2
  SERVER_SSL_CERT: /home/ubuntu/jetconf-conf/server.crt
  SERVER_SSL_PRIVKEY: /home/ubuntu/jetconf-conf/server.key
  UPLOAD_SIZE_LIMIT: 1
KNOT:
  SOCKET: /home/ubuntu/knot-conf/knot.sock
NACM:
  ALLOWED_USERS:
  - lojza@mail.cz
  ENABLED: true

2017-06-29 02:45:34,913 INFO     Server started on ('::', 8443, 0, 0)

However I got errors out when I tried to send a request using curl:

 curl -v  --cert ./example-client.pem  --cacert ./ca.pem  https://localhost:8443/restconf/operations/jetconf:conf-status  

ubuntu@ip-172-26-8-91:~/jetconf-conf$ curl -v   --cert ./example-client.pem  --cacert ./ca.pem  https://localhost:8443/restconf/operations/jetconf:conf-status  *   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* found 1 certificates in ./ca.pem
* found 696 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* server certificate verification failed. CAfile: ./ca.pem CRLfile: none
* Closing connection 0
curl: (60) server certificate verification failed. CAfile: ./ca.pem CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.


If I use curl -k option to skip server cert validation, I got:
ubuntu@ip-172-26-8-91:~/jetconf-conf$ curl -v  -k  -cert ./example-client.pem  --cacert ./ca.pem  https://localhost:8443/restconf/operations/jetconf:conf-status
* Could not resolve host:
* Closing connection 0
curl: (6) Could not resolve host:
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#1)
* found 1 certificates in ./ca.pem
* found 696 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: Error in the push function.
* Closing connection 1
curl: (35) gnutls_handshake() failed: Error in the push function.
ubuntu@ip-172-26-8-91:~/jetconf-conf$ curl -v  -k  --cert ./example-client.pem  --cacert ./ca.pem  https://localhost:8443/restconf/operations/jetconf:conf-status
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* found 1 certificates in ./ca.pem
* found 696 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: 127.0.0.1.xip.io (does not match 'localhost')
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=127.0.0.1.xip.io
*        start date: Wed, 10 Dec 2014 19:33:05 GMT
*        expire date: Sat, 07 Dec 2024 19:33:05 GMT
*        issuer: CN=H2O Test CA
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /restconf/operations/jetconf:conf-status HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.47.0
> Accept: */*

and the server side also emits the following error:

2017-06-29 02:45:34,913 INFO     Server started on ('::', 8443, 0, 0)
2017-06-29 02:49:47,151 ERROR    Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/opt/python3.6.1/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/opt/python3.6.1/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/opt/python3.6.1/lib/python3.6/asyncio/sslproto.py", line 516, in data_received
    self._app_protocol.data_received(chunk)
  File "/opt/python3.6.1/lib/python3.6/site-packages/jetconf-0.1.2.dev74+g5336c3a-py3.6.egg/jetconf/rest_server.py", line 75, in data_received
    events = self.conn.receive_data(data)
  File "/opt/python3.6.1/lib/python3.6/site-packages/h2/connection.py", line 1526, in receive_data
    self.incoming_buffer.add_data(data)
  File "/opt/python3.6.1/lib/python3.6/site-packages/h2/frame_buffer.py", line 52, in add_data
    raise ProtocolError("Invalid HTTP/2 preamble.")
h2.exceptions.ProtocolError: Invalid HTTP/2 preamble.


I made sure I am now using the exact same version of packages as listed in requirements.txt
Please help to to see what went wrong.

Best regards,
-Xiang

**Comment by pspirek** [comment]
Hello, the certificate problem is exactly what you are saying, the testing certificate is not issued by a trusted authority and its CNAME field does not match localhost etc... If you just want to test Jetconf, just pass the `-k` option to curl, like you did.

And to your second problem - you have to explicitly tell curl to enable HTTP/2 with `--http2` option. Also RESTCONF operations need to be called using POST method, not GET like you are trying to do. Anyway thanks for your bug report, that unhandled exception should of course never happen ;)

The complete command will be like this:
`curl --http2 -k --cert-type PEM -E /path/to/client_cert.pem -X POST "https://127.0.0.1:8443/restconf/operations/jetconf:conf-status"`

Please note that curl needs to be compiled with HTTP/2 support, otherwise it will just return an "Unsupported protocol" error.

**Comment by xianglisegue** [comment]
thank you very much for the help! I can now start jetconf and also send some quests.
I think you might have done some updates since I do not need to use --http2 option with curl this morning and things worked.

About -k option, if I regenerate  and self-sign a new server certificate using the data/ca.pem, I can use --cacert ca.pem with curl to talk to the server successfully. It appears that the server.crt in jetconf/data folder was not signed by ca.pem.

I will play with it a bit. Thanks again!
Best regards,
-Xiang
