### ISSUE TITLE
Root Resource Discovery

### ISSUE THREAD

**Issue by GrumpyOldTroll** [CZ-NIC/jetconf#9]
Hi, it looks like the default jetconf install doesn't implement Root Resource Discovery (<https://tools.ietf.org/html/rfc8040#section-3.1>).

Expected behavior:

~~~
$ curl ... -D - https://localhost:8443/.well-known/host-meta
...
Content-Type: application/xrd+xml

<XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'>
    <Link rel='restconf' href='/restconf'/>
</XRD>
~~~

I find I can sort of work around this by adding a "host-meta" file in a ".well-known" directory under the doc root, but I'm not clear how to set the content-type?

Also, ideally this would be present in the default config :)

**Comment by alesmrazek** [comment]
Hi, I added automatic choice of `content-type` for `.well-known/host-meta` URI. I also added automatic `.well-known/host-meta` file creation on Jetconf startup.
